; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29111.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__FC8B975D_vcruntime_new@h DB 01H
__F4CA4DDB_cstddef DB 01H
__09340588_corecrt_math@h DB 01H
__24E9E95F_stdlib@h DB 01H
__51019776_cstdlib DB 01H
__B236D4B0_type_traits DB 01H
__B0C4CEA9_malloc@h DB 01H
__18D87206_vcruntime_exception@h DB 01H
__1302BCB8_exception DB 01H
__F66CEB67_corecrt_stdio_config@h DB 01H
__101834BA_corecrt_wstdio@h DB 01H
__AD6A91B7_stdio@h DB 01H
__367CC694_corecrt_memcpy_s@h DB 01H
__35D7DDB3_corecrt_memory@h DB 01H
__DC9673E3_corecrt_wstring@h DB 01H
__A29A7DFB_string@h DB 01H
__5467428D_corecrt_wconio@h DB 01H
__4442441F_corecrt_wio@h DB 01H
__45F4AF76_corecrt_wtime@h DB 01H
__186FF47F_stat@h DB 01H
__534C724A_wchar@h DB 01H
__7B3ADE64_vcruntime_typeinfo@h DB 01H
__4638863E_typeinfo DB 01H
__5E219BC0_limits DB 01H
__36E77527_xutility DB 01H
__0C99713E_xmemory DB 01H
__E28F974E_memory DB 01H
__B6041EFB_tuple DB 01H
__04937CFC_xpolymorphic_allocator@h DB 01H
__784AF7A2_xstring DB 01H
__7242C389_ctype@h DB 01H
__965C11D2_string DB 01H
__9A4C86E5_stdexcept DB 01H
__102707BA_cmath DB 01H
__238A5427_xcall_once@h DB 01H
__3514C702_atomic DB 01H
__9CD74607_system_error DB 01H
__CECAC041_xfacet DB 01H
__59B165F6_xlocinfo DB 01H
__A7748393_xlocale DB 01H
__605412E5_xiosbase DB 01H
__39F3E584_xlocnum DB 01H
__D3011E72_ios DB 01H
__E02C27BD_LoggerHandler@hpp DB 01H
__190EFBB8_xtree DB 01H
__6E56F6D1_PersistenceHandler@cpp DB 01H
__D7B46C6D_istream DB 01H
__B4645957_ostream DB 01H
__98EC3E59_streambuf DB 01H
__92C84E46_iosfwd DB 01H
__660C12FD_utility DB 01H
__274BC267_iterator DB 01H
__911385EF_xstddef DB 01H
__190E306E_xatomic@h DB 01H
msvcjmc	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAXW4align_val_t@std@@@Z ; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_KW4align_val_t@std@@@Z ; __empty_global_delete
PUBLIC	?instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ ; TechnicalServices::Persistence::PersistenceHandler::instance
PUBLIC	??1PersistenceHandler@Persistence@TechnicalServices@@UEAA@XZ ; TechnicalServices::Persistence::PersistenceHandler::~PersistenceHandler
PUBLIC	?__autoclassinit2@SimpleDB@Persistence@TechnicalServices@@QEAAX_K@Z ; TechnicalServices::Persistence::SimpleDB::__autoclassinit2
PUBLIC	__JustMyCode_Default
PUBLIC	??_7PersistenceHandler@Persistence@TechnicalServices@@6B@ ; TechnicalServices::Persistence::PersistenceHandler::`vftable'
PUBLIC	??_R4PersistenceHandler@Persistence@TechnicalServices@@6B@ ; TechnicalServices::Persistence::PersistenceHandler::`RTTI Complete Object Locator'
PUBLIC	??_R0?AVPersistenceHandler@Persistence@TechnicalServices@@@8 ; TechnicalServices::Persistence::PersistenceHandler `RTTI Type Descriptor'
PUBLIC	??_R3PersistenceHandler@Persistence@TechnicalServices@@8 ; TechnicalServices::Persistence::PersistenceHandler::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2PersistenceHandler@Persistence@TechnicalServices@@8 ; TechnicalServices::Persistence::PersistenceHandler::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@PersistenceHandler@Persistence@TechnicalServices@@8 ; TechnicalServices::Persistence::PersistenceHandler::`RTTI Base Class Descriptor at (0,-1,0,64)'
EXTRN	_purecall:PROC
EXTRN	atexit:PROC
EXTRN	_Init_thread_header:PROC
EXTRN	_Init_thread_abort:PROC
EXTRN	_Init_thread_footer:PROC
EXTRN	??0SimpleDB@Persistence@TechnicalServices@@QEAA@XZ:PROC ; TechnicalServices::Persistence::SimpleDB::SimpleDB
EXTRN	??1SimpleDB@Persistence@TechnicalServices@@UEAA@XZ:PROC ; TechnicalServices::Persistence::SimpleDB::~SimpleDB
EXTRN	_RTC_InitBase:PROC
EXTRN	_RTC_Shutdown:PROC
EXTRN	__CheckForDebuggerJustMyCode:PROC
EXTRN	__CxxFrameHandler4:PROC
EXTRN	_Init_thread_epoch:DWORD
EXTRN	??_7type_info@@6B@:BYTE				; type_info::`vftable'
EXTRN	_tls_index:DWORD
_BSS	SEGMENT
?instance@?1??0PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@4VSimpleDB@23@A DB 030H DUP (?) ; `TechnicalServices::Persistence::PersistenceHandler::instance'::`2'::instance
?$TSS0@?1??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV234@XZ@4HA DD 01H DUP (?) ; `TechnicalServices::Persistence::PersistenceHandler::instance'::`2'::$TSS0
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAX@Z DD imagerel $LN3
	DD	imagerel $LN3+65
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAX_K@Z DD imagerel $LN3
	DD	imagerel $LN3+70
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAX_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAXW4align_val_t@std@@@Z DD imagerel $LN3
	DD	imagerel $LN3+70
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAXW4align_val_t@std@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAX_KW4align_val_t@std@@@Z DD imagerel $LN3
	DD	imagerel $LN3+75
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAX_KW4align_val_t@std@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ DD imagerel $LN5
	DD	imagerel $LN5+171
	DD	imagerel $unwind$?instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?dtor$0@?0??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@4HA DD imagerel ?dtor$0@?0??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@4HA
	DD	imagerel ?dtor$0@?0??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@4HA+39
	DD	imagerel $unwind$?dtor$0@?0??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@4HA
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1PersistenceHandler@Persistence@TechnicalServices@@UEAA@XZ DD imagerel $LN3
	DD	imagerel $LN3+81
	DD	imagerel $unwind$??1PersistenceHandler@Persistence@TechnicalServices@@UEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__autoclassinit2@SimpleDB@Persistence@TechnicalServices@@QEAAX_K@Z DD imagerel $LN3
	DD	imagerel $LN3+73
	DD	imagerel $unwind$?__autoclassinit2@SimpleDB@Persistence@TechnicalServices@@QEAAX_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__Finstance@?1??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@YAXXZ DD imagerel ??__Finstance@?1??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@YAXXZ
	DD	imagerel ??__Finstance@?1??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@YAXXZ+52
	DD	imagerel $unwind$??__Finstance@?1??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@YAXXZ
pdata	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
_RTC_Shutdown.rtc$TMZ DQ FLAT:_RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
_RTC_InitBase.rtc$IMZ DQ FLAT:_RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT ??_R1A@?0A@EA@PersistenceHandler@Persistence@TechnicalServices@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@PersistenceHandler@Persistence@TechnicalServices@@8 DD imagerel ??_R0?AVPersistenceHandler@Persistence@TechnicalServices@@@8 ; TechnicalServices::Persistence::PersistenceHandler::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3PersistenceHandler@Persistence@TechnicalServices@@8
rdata$r	ENDS
;	COMDAT ??_R2PersistenceHandler@Persistence@TechnicalServices@@8
rdata$r	SEGMENT
??_R2PersistenceHandler@Persistence@TechnicalServices@@8 DD imagerel ??_R1A@?0A@EA@PersistenceHandler@Persistence@TechnicalServices@@8 ; TechnicalServices::Persistence::PersistenceHandler::`RTTI Base Class Array'
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_R3PersistenceHandler@Persistence@TechnicalServices@@8
rdata$r	SEGMENT
??_R3PersistenceHandler@Persistence@TechnicalServices@@8 DD 00H ; TechnicalServices::Persistence::PersistenceHandler::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	imagerel ??_R2PersistenceHandler@Persistence@TechnicalServices@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVPersistenceHandler@Persistence@TechnicalServices@@@8
data$r	SEGMENT
??_R0?AVPersistenceHandler@Persistence@TechnicalServices@@@8 DQ FLAT:??_7type_info@@6B@ ; TechnicalServices::Persistence::PersistenceHandler `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVPersistenceHandler@Persistence@TechnicalServices@@', 00H
data$r	ENDS
;	COMDAT ??_R4PersistenceHandler@Persistence@TechnicalServices@@6B@
rdata$r	SEGMENT
??_R4PersistenceHandler@Persistence@TechnicalServices@@6B@ DD 01H ; TechnicalServices::Persistence::PersistenceHandler::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVPersistenceHandler@Persistence@TechnicalServices@@@8
	DD	imagerel ??_R3PersistenceHandler@Persistence@TechnicalServices@@8
	DD	imagerel ??_R4PersistenceHandler@Persistence@TechnicalServices@@6B@
rdata$r	ENDS
;	COMDAT ??_7PersistenceHandler@Persistence@TechnicalServices@@6B@
CONST	SEGMENT
??_7PersistenceHandler@Persistence@TechnicalServices@@6B@ DQ FLAT:??_R4PersistenceHandler@Persistence@TechnicalServices@@6B@ ; TechnicalServices::Persistence::PersistenceHandler::`vftable'
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
	DQ	FLAT:_purecall
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__Finstance@?1??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@YAXXZ DD 025051e01H
	DD	010a230fH
	DD	07003001dH
	DD	05002H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__autoclassinit2@SimpleDB@Persistence@TechnicalServices@@QEAAX_K@Z DD 05052d01H
	DD	01130316H
	DD	0700c0019H
	DD	0500bH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??1PersistenceHandler@Persistence@TechnicalServices@@UEAA@XZ DB 02H
	DB	00H
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??1PersistenceHandler@Persistence@TechnicalServices@@UEAA@XZ DB 060H
	DD	imagerel $ip2state$??1PersistenceHandler@Persistence@TechnicalServices@@UEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1PersistenceHandler@Persistence@TechnicalServices@@UEAA@XZ DD 025052a19H
	DD	010e2313H
	DD	07007001dH
	DD	05006H
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$??1PersistenceHandler@Persistence@TechnicalServices@@UEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?dtor$0@?0??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@4HA DD 031001H
	DD	0700c4210H
	DD	0500bH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ DB 06H
	DB	00H
	DB	00H
	DB	0c8H
	DB	02H
	DB	'T'
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ DB 02H
	DB	0eH
	DD	imagerel ?dtor$0@?0??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@4HA
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ DB 028H
	DD	imagerel $stateUnwindMap$?instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ
	DD	imagerel $ip2state$?instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ DD 025051e11H
	DD	010a230fH
	DD	07003001dH
	DD	05002H
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$?instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?__empty_global_delete@@YAXPEAX_KW4align_val_t@std@@@Z DB 02H
	DB	00H
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?__empty_global_delete@@YAXPEAX_KW4align_val_t@std@@@Z DB 060H
	DD	imagerel $ip2state$?__empty_global_delete@@YAXPEAX_KW4align_val_t@std@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAX_KW4align_val_t@std@@@Z DD 025053419H
	DD	0118231dH
	DD	07011001dH
	DD	05010H
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$?__empty_global_delete@@YAXPEAX_KW4align_val_t@std@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?__empty_global_delete@@YAXPEAXW4align_val_t@std@@@Z DB 02H
	DB	00H
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?__empty_global_delete@@YAXPEAXW4align_val_t@std@@@Z DB 060H
	DD	imagerel $ip2state$?__empty_global_delete@@YAXPEAXW4align_val_t@std@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAXW4align_val_t@std@@@Z DD 025052f19H
	DD	01132318H
	DD	0700c001dH
	DD	0500bH
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$?__empty_global_delete@@YAXPEAXW4align_val_t@std@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?__empty_global_delete@@YAXPEAX_K@Z DB 02H
	DB	00H
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?__empty_global_delete@@YAXPEAX_K@Z DB 060H
	DD	imagerel $ip2state$?__empty_global_delete@@YAXPEAX_K@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAX_K@Z DD 025052f19H
	DD	01132318H
	DD	0700c001dH
	DD	0500bH
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$?__empty_global_delete@@YAXPEAX_K@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?__empty_global_delete@@YAXPEAX@Z DB 02H
	DB	00H
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?__empty_global_delete@@YAXPEAX@Z DB 060H
	DD	imagerel $ip2state$?__empty_global_delete@@YAXPEAX@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAX@Z DD 025052a19H
	DD	010e2313H
	DD	07007001dH
	DD	05006H
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$?__empty_global_delete@@YAXPEAX@Z
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??__Finstance@?1??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@YAXXZ
text$yd	SEGMENT
??__Finstance@?1??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@YAXXZ PROC ; `TechnicalServices::Persistence::PersistenceHandler::instance'::`2'::`dynamic atexit destructor for 'instance'', COMDAT
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	lea	rcx, OFFSET FLAT:?instance@?1??0PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@4VSimpleDB@23@A
	call	??1SimpleDB@Persistence@TechnicalServices@@UEAA@XZ ; TechnicalServices::Persistence::SimpleDB::~SimpleDB
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
??__Finstance@?1??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@YAXXZ ENDP ; `TechnicalServices::Persistence::PersistenceHandler::instance'::`2'::`dynamic atexit destructor for 'instance''
text$yd	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?__autoclassinit2@SimpleDB@Persistence@TechnicalServices@@QEAAX_K@Z
_TEXT	SEGMENT
this$ = 224
classSize$ = 232
?__autoclassinit2@SimpleDB@Persistence@TechnicalServices@@QEAAX_K@Z PROC ; TechnicalServices::Persistence::SimpleDB::__autoclassinit2, COMDAT
$LN3:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 200				; 000000c8H
	mov	rbp, rsp
	mov	rdi, rsp
	mov	ecx, 50					; 00000032H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+232]
	mov	rdi, QWORD PTR this$[rbp]
	xor	eax, eax
	mov	rcx, QWORD PTR classSize$[rbp]
	rep stosb
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
?__autoclassinit2@SimpleDB@Persistence@TechnicalServices@@QEAAX_K@Z ENDP ; TechnicalServices::Persistence::SimpleDB::__autoclassinit2
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\dpham181\Desktop\CPSC462\CPSC-462-GROUP-2\C++ Development Root\SourceCode\TechnicalServices\Persistence\PersistenceHandler.cpp
;	COMDAT ??1PersistenceHandler@Persistence@TechnicalServices@@UEAA@XZ
_TEXT	SEGMENT
this$ = 224
??1PersistenceHandler@Persistence@TechnicalServices@@UEAA@XZ PROC ; TechnicalServices::Persistence::PersistenceHandler::~PersistenceHandler, COMDAT

; 6    :   PersistenceHandler::~PersistenceHandler() noexcept = default;

$LN3:
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+264]
	lea	rcx, OFFSET FLAT:__6E56F6D1_PersistenceHandler@cpp
	call	__CheckForDebuggerJustMyCode
	mov	rax, QWORD PTR this$[rbp]
	lea	rcx, OFFSET FLAT:??_7PersistenceHandler@Persistence@TechnicalServices@@6B@
	mov	QWORD PTR [rax], rcx
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
??1PersistenceHandler@Persistence@TechnicalServices@@UEAA@XZ ENDP ; TechnicalServices::Persistence::PersistenceHandler::~PersistenceHandler
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\dpham181\Desktop\CPSC462\CPSC-462-GROUP-2\C++ Development Root\SourceCode\TechnicalServices\Persistence\PersistenceHandler.cpp
;	COMDAT ?instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ
_TEXT	SEGMENT
?instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ PROC ; TechnicalServices::Persistence::PersistenceHandler::instance, COMDAT

; 12   :   {

$LN5:
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	lea	rcx, OFFSET FLAT:__6E56F6D1_PersistenceHandler@cpp
	call	__CheckForDebuggerJustMyCode

; 13   :     // Can't read the DB component preference from the database because the DB has not yet been created. So choosing the database
; 14   :     // implementation is really a configuration item (set by the vendor before delivery), not an adaptable item (set by the end-user
; 15   :     // after delivery)
; 16   :     using SelectedDatabase = SimpleDB;
; 17   : 
; 18   :     static SelectedDatabase instance;    // Note the creation of a DB specialization (derived class), but returning a reference to

	mov	eax, OFFSET FLAT:_Init_thread_epoch
	mov	eax, eax
	mov	ecx, DWORD PTR _tls_index
	mov	rdx, QWORD PTR gs:88
	mov	rcx, QWORD PTR [rdx+rcx*8]
	mov	eax, DWORD PTR [rax+rcx]
	cmp	DWORD PTR ?$TSS0@?1??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV234@XZ@4HA, eax
	jle	SHORT $LN2@instance
	lea	rcx, OFFSET FLAT:?$TSS0@?1??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV234@XZ@4HA
	call	_Init_thread_header
	cmp	DWORD PTR ?$TSS0@?1??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV234@XZ@4HA, -1
	jne	SHORT $LN2@instance
	mov	edx, 48					; 00000030H
	lea	rcx, OFFSET FLAT:?instance@?1??0PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@4VSimpleDB@23@A
	call	?__autoclassinit2@SimpleDB@Persistence@TechnicalServices@@QEAAX_K@Z
	lea	rcx, OFFSET FLAT:?instance@?1??0PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@4VSimpleDB@23@A
	call	??0SimpleDB@Persistence@TechnicalServices@@QEAA@XZ ; TechnicalServices::Persistence::SimpleDB::SimpleDB
	lea	rcx, OFFSET FLAT:??__Finstance@?1??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@YAXXZ ; `TechnicalServices::Persistence::PersistenceHandler::instance'::`2'::`dynamic atexit destructor for 'instance''
	call	atexit
	npad	1
	lea	rcx, OFFSET FLAT:?$TSS0@?1??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV234@XZ@4HA
	call	_Init_thread_footer
$LN2@instance:

; 19   :                                          // the generalization (base class). Since SimpleDB is-a PersistenceHandler, we can return a
; 20   :                                          // reference to the base class that refers to a specific derived class.  SimpleDB is
; 21   :                                          // accessed polymorphicly through the PersistenceHandler interface.  This source file knows
; 22   :                                          // about the specific SimpleDB derived class, but that's okay.  This source file is not
; 23   :                                          // delivered with the interface and remains That is, PersistenceHandler.hpp is given to the
; 24   :                                          // upper architectural layers, but not PersistenceHandler.cpp.
; 25   :     return instance;

	lea	rax, OFFSET FLAT:?instance@?1??0PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@4VSimpleDB@23@A

; 26   :   }

	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
?instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ ENDP ; TechnicalServices::Persistence::PersistenceHandler::instance
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
?dtor$0@?0??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@4HA PROC ; `TechnicalServices::Persistence::PersistenceHandler::instance'::`1'::dtor$0
	mov	QWORD PTR [rsp+8], rcx
	mov	QWORD PTR [rsp+16], rdx
	push	rbp
	push	rdi
	sub	rsp, 40					; 00000028H
	lea	rbp, QWORD PTR [rdx+32]
	lea	rcx, OFFSET FLAT:?$TSS0@?1??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV234@XZ@4HA
	call	_Init_thread_abort
	add	rsp, 40					; 00000028H
	pop	rdi
	pop	rbp
	ret	0
?dtor$0@?0??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@4HA ENDP ; `TechnicalServices::Persistence::PersistenceHandler::instance'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT text$x
text$x	SEGMENT
?dtor$0@?0??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@4HA PROC ; `TechnicalServices::Persistence::PersistenceHandler::instance'::`1'::dtor$0
	mov	QWORD PTR [rsp+8], rcx
	mov	QWORD PTR [rsp+16], rdx
	push	rbp
	push	rdi
	sub	rsp, 40					; 00000028H
	lea	rbp, QWORD PTR [rdx+32]
	lea	rcx, OFFSET FLAT:?$TSS0@?1??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV234@XZ@4HA
	call	_Init_thread_abort
	add	rsp, 40					; 00000028H
	pop	rdi
	pop	rbp
	ret	0
?dtor$0@?0??instance@PersistenceHandler@Persistence@TechnicalServices@@SAAEAV123@XZ@4HA ENDP ; `TechnicalServices::Persistence::PersistenceHandler::instance'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\dpham181\Desktop\CPSC462\CPSC-462-GROUP-2\C++ Development Root\SourceCode\TechnicalServices\Persistence\PersistenceHandler.cpp
;	COMDAT ?__empty_global_delete@@YAXPEAX_KW4align_val_t@std@@@Z
_TEXT	SEGMENT
__formal$ = 224
__formal$ = 232
__formal$ = 240
?__empty_global_delete@@YAXPEAX_KW4align_val_t@std@@@Z PROC ; __empty_global_delete, COMDAT

$LN3:
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+264]
	lea	rcx, OFFSET FLAT:__6E56F6D1_PersistenceHandler@cpp
	call	__CheckForDebuggerJustMyCode
	npad	1
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAX_KW4align_val_t@std@@@Z ENDP ; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\dpham181\Desktop\CPSC462\CPSC-462-GROUP-2\C++ Development Root\SourceCode\TechnicalServices\Persistence\PersistenceHandler.cpp
;	COMDAT ?__empty_global_delete@@YAXPEAXW4align_val_t@std@@@Z
_TEXT	SEGMENT
__formal$ = 224
__formal$ = 232
?__empty_global_delete@@YAXPEAXW4align_val_t@std@@@Z PROC ; __empty_global_delete, COMDAT

$LN3:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+264]
	lea	rcx, OFFSET FLAT:__6E56F6D1_PersistenceHandler@cpp
	call	__CheckForDebuggerJustMyCode
	npad	1
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAXW4align_val_t@std@@@Z ENDP ; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\dpham181\Desktop\CPSC462\CPSC-462-GROUP-2\C++ Development Root\SourceCode\TechnicalServices\Persistence\PersistenceHandler.cpp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 224
__formal$ = 232
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT

$LN3:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+264]
	lea	rcx, OFFSET FLAT:__6E56F6D1_PersistenceHandler@cpp
	call	__CheckForDebuggerJustMyCode
	npad	1
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\dpham181\Desktop\CPSC462\CPSC-462-GROUP-2\C++ Development Root\SourceCode\TechnicalServices\Persistence\PersistenceHandler.cpp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 224
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT

$LN3:
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+264]
	lea	rcx, OFFSET FLAT:__6E56F6D1_PersistenceHandler@cpp
	call	__CheckForDebuggerJustMyCode
	npad	1
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
